### ISSUE TITLE
Finish Linode details page

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#302]
This is a master list identifying all the issues involved in finishing the Linode details page (in our arbitrary alpha scope):

* Backups
  * [ ] [Get real backups price](https://github.com/linode/manager/issues/279)
  * [x] [Implement backup schedule editing](https://github.com/linode/manager/issues/274)
  * [x] [Implement restore to new Linode](https://github.com/linode/manager/issues/174)
* Networking
  * [ ] [Implement networking tabs](https://github.com/linode/manager/issues/185)
  * [ ] [Implement add an ip modal](https://github.com/linode/manager/issues/259)
  * [ ] [Implement IP removal tab and modal](https://github.com/linode/manager/issues/258)
  * [ ] [Implement IP swap tab](https://github.com/linode/manager/issues/260)
  * [ ] [Implement IP sharing tab](https://github.com/linode/manager/issues/261)
  * [ ] [Implement IP RDNS tab](https://github.com/linode/manager/issues/262)
* Advanced
  * [x] Finalize tab and create tasks for result
* [x] [Repair](https://github.com/linode/manager/issues/33)
* [ ] [Rescue](https://github.com/linode/manager/issues/33)
* [ ] [Resize](https://github.com/linode/manager/issues/45)
