### ISSUE TITLE
Finish Linode create page

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#304]
This is a master list identifying all the issues involved in finishing the Linode create page (in our arbitrary alpha scope):

* [ ] [Show steps completed](https://github.com/linode/manager/issues/281)
* [x] [Add group/quantity](https://github.com/linode/manager/issues/235)
* [x] [Implement enable backups](https://github.com/linode/manager/issues/251)
* [ ] [Discuss and implement stackscripts](https://github.com/linode/manager/issues/193)
* [ ] [Mockup/implement clone Linode](https://github.com/linode/manager/issues/195) ?
