### ISSUE TITLE
Responsivness problems meta-issue

### ISSUE THREAD

**Issue by SirCmpwn** [linode/manager#76]
- [ ] Linode detail page @ <1000px wide
- [ ] Linode grid view @ <1100px wide
- [ ] Linode list view @ <1000px wide

**Comment by eatonphil** [comment]
This was dealt with in #659
